"use client";

import { useState, useEffect, useCallback } from "react";
import Link from "next/link";
import { Sparkles, Send, Loader2, Zap, BookOpen, ArrowLeft, AlertCircle } from "lucide-react";
import { Markdown } from "@/components/markdown";

interface SkillListItem {
  slug: string;
  name: string;
  description: string;
  category?: string;
  version: string;
  suite: { slug: string; name: string };
  pricePerUse?: number;
  subscriptionPrice?: number;
}

interface Attribution {
  source_title?: string;
  source_authors?: string[];
  source_license?: string;
}

interface InvokeResponse {
  success: boolean;
  mode: "live" | "demo";
  output: string;
  skill: { slug: string; name: string };
  attribution: Attribution | null;
  usage: { model: string | null; inputTokens: number | null; outputTokens: number | null; durationMs: number };
}

const MAX_INPUT = 4000;

export default function DemoPage() {
  const [skills, setSkills] = useState<SkillListItem[]>([]);
  const [mode, setMode] = useState<"live" | "demo">("demo");
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [selected, setSelected] = useState<SkillListItem | null>(null);
  const [input, setInput] = useState("");
  const [result, setResult] = useState<InvokeResponse | null>(null);
  const [invokeError, setInvokeError] = useState<string | null>(null);
  const [invoking, setInvoking] = useState(false);

  const fetchSkills = useCallback(async () => {
    setLoading(true);
    setLoadError(null);
    try {
      const res = await fetch("/api/skills");
      if (!res.ok) throw new Error("Failed to load skills.");
      const data = await res.json();
      setSkills(data.skills ?? []);
      setMode(data.mode ?? "demo");
    } catch {
      setLoadError("Could not load skills. Please refresh.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchSkills();
  }, [fetchSkills]);

  const invokeSkill = async () => {
    if (!selected || !input.trim() || invoking) return;
    setInvoking(true);
    setResult(null);
    setInvokeError(null);
    try {
      const res = await fetch("/api/skills/invoke", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ slug: selected.slug, input }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        setInvokeError(data.error ?? "Skill execution failed.");
        return;
      }
      setResult(data);
    } catch {
      setInvokeError("Network error. Please try again.");
    } finally {
      setInvoking(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      <div className="max-w-6xl mx-auto px-4 py-12">
        {/* Header */}
        <div className="text-center mb-10">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-purple-200 hover:text-white transition-colors mb-6"
          >
            <ArrowLeft className="w-4 h-4" /> Back to overview
          </Link>
          <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-r from-amber-400 to-orange-500 rounded-2xl mb-4">
            <Sparkles className="w-8 h-8 text-slate-900" />
          </div>
          <h1 className="text-4xl font-bold text-white mb-3">Skill Execution Demo</h1>
          <p className="text-purple-200 max-w-2xl mx-auto">
            Pick a skill, describe your situation, and run it. Each skill applies a methodology drawn from published
            knowledge — with attribution carried through to the response.
          </p>
          <div className="mt-5 inline-flex items-center gap-2 rounded-full px-4 py-1.5 text-sm font-medium bg-slate-800/70 border border-slate-700 text-slate-200">
            <span className={`w-2 h-2 rounded-full ${mode === "live" ? "bg-green-400" : "bg-amber-400"}`} />
            {mode === "live" ? "Live mode — responses generated by a language model" : "Demo mode — local responses (no model key configured)"}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Skills List */}
          <div className="lg:col-span-1">
            <div className="bg-slate-800/50 backdrop-blur border border-slate-700 rounded-2xl p-6">
              <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-amber-400" />
                Available Skills
                {!loading && <span className="text-sm font-normal text-slate-400">({skills.length})</span>}
              </h2>

              {loading ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="w-6 h-6 text-purple-400 animate-spin" />
                </div>
              ) : loadError ? (
                <div className="text-center py-8 text-slate-400">
                  <p className="mb-3">{loadError}</p>
                  <button onClick={fetchSkills} className="text-amber-400 hover:text-amber-300 text-sm font-medium">
                    Retry
                  </button>
                </div>
              ) : skills.length === 0 ? (
                <p className="text-slate-400 text-center py-8">No skills available yet.</p>
              ) : (
                <div className="space-y-3">
                  {skills.map((skill) => (
                    <button
                      key={skill.slug}
                      onClick={() => {
                        setSelected(skill);
                        setResult(null);
                        setInvokeError(null);
                      }}
                      className={`w-full text-left p-4 rounded-xl transition-all ${
                        selected?.slug === skill.slug
                          ? "bg-gradient-to-r from-amber-500/20 to-orange-500/20 border-2 border-amber-400/50"
                          : "bg-slate-700/30 border-2 border-transparent hover:border-slate-600"
                      }`}
                    >
                      <div className="font-medium text-white">{skill.name}</div>
                      <div className="text-sm text-slate-400 mt-1 line-clamp-2">{skill.description}</div>
                      <div className="text-xs text-purple-300 mt-2">From: {skill.suite.name}</div>
                      {skill.pricePerUse != null && (
                        <div className="flex items-center gap-1 text-xs text-amber-400 mt-2">
                          <Zap className="w-3 h-3" />
                          {skill.pricePerUse} sats/use <span className="text-slate-500">(indicative)</span>
                        </div>
                      )}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Invocation Interface */}
          <div className="lg:col-span-2">
            {selected ? (
              <div className="bg-slate-800/50 backdrop-blur border border-slate-700 rounded-2xl p-6">
                <div className="flex items-start justify-between mb-6 gap-4">
                  <div>
                    <h2 className="text-xl font-semibold text-white">Invoke: {selected.name}</h2>
                    <p className="text-sm text-slate-400 mt-1">{selected.description}</p>
                  </div>
                  <div
                    className={`px-3 py-1 rounded-full text-sm whitespace-nowrap ${
                      mode === "live" ? "bg-green-500/20 text-green-300" : "bg-amber-500/20 text-amber-400"
                    }`}
                  >
                    {mode === "live" ? "Live" : "Demo"}
                  </div>
                </div>

                <div className="mb-2">
                  <label htmlFor="prompt" className="block text-sm font-medium text-slate-300 mb-2">
                    Your prompt
                  </label>
                  <textarea
                    id="prompt"
                    value={input}
                    maxLength={MAX_INPUT}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder={`e.g. "How could I apply ${selected.name} to a campaign for safer streets in my town?"`}
                    className="w-full h-32 bg-slate-900/50 border border-slate-600 rounded-xl p-4 text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-amber-400/50 resize-none"
                  />
                  <div className="text-right text-xs text-slate-500 mt-1">
                    {input.length} / {MAX_INPUT}
                  </div>
                </div>

                <button
                  onClick={invokeSkill}
                  disabled={invoking || !input.trim()}
                  className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 disabled:from-slate-600 disabled:to-slate-600 text-slate-900 font-semibold py-3 px-6 rounded-xl transition-all disabled:cursor-not-allowed"
                >
                  {invoking ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" /> Running…
                    </>
                  ) : (
                    <>
                      <Send className="w-5 h-5" /> Invoke skill
                    </>
                  )}
                </button>

                {invokeError && (
                  <div className="mt-6 flex items-start gap-2 bg-red-900/30 border border-red-700/50 rounded-xl p-4 text-red-200 text-sm">
                    <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                    <span>{invokeError}</span>
                  </div>
                )}

                {result && (
                  <div className="mt-6">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium text-slate-300">Response</span>
                      {result.usage.model && (
                        <span className="text-xs text-slate-500">
                          {result.usage.model} · {result.usage.outputTokens ?? "?"} tokens · {result.usage.durationMs}ms
                        </span>
                      )}
                    </div>
                    <div className="bg-slate-900/50 border border-slate-600 rounded-xl p-5 text-purple-100">
                      <Markdown>{result.output}</Markdown>
                    </div>
                    {result.attribution?.source_title && (
                      <p className="text-xs text-slate-500 mt-3">
                        Source: <span className="text-slate-400">{result.attribution.source_title}</span>
                        {result.attribution.source_authors?.length
                          ? ` — ${result.attribution.source_authors.join(", ")}`
                          : ""}
                        {result.attribution.source_license ? ` (${result.attribution.source_license})` : ""}
                      </p>
                    )}
                  </div>
                )}
              </div>
            ) : (
              <div className="bg-slate-800/50 backdrop-blur border border-slate-700 rounded-2xl p-12 text-center">
                <Sparkles className="w-16 h-16 text-slate-600 mx-auto mb-4" />
                <h3 className="text-xl font-medium text-white mb-2">Select a skill</h3>
                <p className="text-slate-400">Choose a skill from the list to try invoking it.</p>
              </div>
            )}

            <div className="mt-6 bg-blue-900/20 border border-blue-700/50 rounded-xl p-4">
              <h4 className="text-blue-300 font-medium mb-2">About this demo</h4>
              <p className="text-blue-200/70 text-sm">
                Skills are authored as <code className="font-mono">SKILL.md</code> files; their content is what grounds
                each response, with source attribution attached. The Nostr/Lightning payment rails described on the
                overview page are part of the designed architecture and are not active in this demo.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
