import { NextResponse } from "next/server";
import { db } from "@/db";
import { skills, skillInvocations } from "@/db/schema";
import { eq } from "drizzle-orm";

// POST /api/skills/invoke - Execute a skill (demo/mock implementation)
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { skillId, input, userId } = body;

    if (!skillId || !input) {
      return NextResponse.json(
        { error: "skillId and input are required" },
        { status: 400 }
      );
    }

    // Fetch the skill
    const [skill] = await db
      .select()
      .from(skills)
      .where(eq(skills.id, skillId));

    if (!skill) {
      return NextResponse.json(
        { error: "Skill not found" },
        { status: 404 }
      );
    }

    // In a real implementation, this would:
    // 1. Check payment/status
    // 2. Call Maple AI with the skill content as context
    // 3. Return the AI-generated response
    // 
    // For now, we'll simulate a skill execution with mock output
    const startTime = Date.now();
    
    // Mock AI response based on skill content
    const mockOutput = `🔮 **Skill Execution: ${skill.name}**

**Input:** ${input}

**Simulated Response:**
Based on the ${skill.name} methodology, here's my analysis:

${getMockResponse(skill.name, input)}

---
*This is a demo response. In production, this would be generated by Maple AI using the skill's content as context.*`;

    const duration = Date.now() - startTime;

    // Log the invocation
    await db.insert(skillInvocations).values({
      skillId: skill.id,
      userId: userId || null,
      input: JSON.stringify({ prompt: input }),
      output: mockOutput,
      tokensUsed: Math.floor(Math.random() * 500) + 100,
      duration,
    });

    return NextResponse.json({
      success: true,
      output: mockOutput,
      skill: {
        id: skill.id,
        name: skill.name,
      },
      tokensUsed: Math.floor(Math.random() * 500) + 100,
      duration,
    });
  } catch (error) {
    console.error("Error invoking skill:", error);
    return NextResponse.json(
      { error: "Failed to invoke skill" },
      { status: 500 }
    );
  }
}

function getMockResponse(skillName: string, input: string): string {
  const responses: Record<string, string[]> = {
    "culture-jamming": [
      `To apply culture-jamming to "${input}", consider subverting the original message by flipping its meaning or exposing its hidden assumptions.`,
      `A powerful culture-jamming approach would be to remix the dominant narrative around "${input}" with ironic counter-messaging.`,
      `For maximum impact, target the emotional core of "${input}" and redirect it toward a subversive message.`,
    ],
  };

  const key = skillName.toLowerCase().replace(/\s+/g, "-");
  const options = responses[key] || [
    `After analyzing "${input}" through this skill's methodology, I recommend taking a collaborative approach that leverages community wisdom.`,
    `Applying this skill to "${input}" reveals several strategic options for achieving your goals effectively.`,
  ];

  return options[Math.floor(Math.random() * options.length)];
}
